felixdb/urls.py
from django.urls import path
from . import views

app_name = 'felixdb'
urlpatterns = [
    path('', views.index, name='index'),
    path('regifant/<int:regifant_id>/', views.regifant, name='regifant'),
    path('verv/', views.verv, name="verv"),
    path('verv/<int:verv_id>/', views.vervdetalj, name='vervdetalj'),
    path('ukeverv/', views.ukeverv, name="ukeverv"),
    path('ukeverv/<int:ukeverv_id>', views.ukevervdetalj, name="ukevervdetalj"),
    path('aarsoversikt/<int:aar>/', views.aarsoversikt, name='aarsoversikt'),
    path('uker/', views.uker, name='uker'),
    path('uker/<int:ukeaar>', views.ukedetalj, name='ukedetalj'),
]

hjem/urls.py
from django.urls import path
from . import views

app_name = 'hjem'
urlpatterns = [
    path('', views.index, name='index'),
    path('intern/', views.intern, name='intern'),
    path('kontakt/', views.kontakt, name='kontakt'),
    path('techspecs/', views.techspecs, name='techspecs'),
    path('om/', views.om, name='om')
]

regiweb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('intern/felixdb/', include('felixdb.urls')),
    path('intern/festkassen/', include('festkassen.urls')),
    path('intern/wiki/', include('wiki.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('hjem.urls')),
]

felixdb/models.py
from django.db import models
# Create your models here.

class Regifant(models.Model):

    # personalia
    fornavn = models.CharField(max_length=100)
    etternavn = models.CharField(max_length=100)
    kallenavn = models.CharField(max_length=100, blank=True)

    # Regi-info
    er_aktiv = models.BooleanField(default=True)

    # Tid og datoer
    foedt = models.IntegerField(blank=True, null=True)
    doed = models.IntegerField(blank=True, null=True)
    tatt_opp = models.IntegerField(blank=True, null=True)
    pensjonert = models.IntegerField(blank=True, null=True)

    # Kontaktinfo
    mobil = models.CharField(max_length=100, blank=True)
    fasttelefon = models.CharField(max_length=100, blank=True)
    adresse = models.CharField(max_length=100, blank=True)
    postnr = models.CharField(max_length=100, blank=True)
    poststed = models.CharField(max_length=100, blank=True)
    email = models.EmailField(blank=True)
    hjemmeadresse = models.CharField(max_length=100, blank=True)
    hjemmepostnr = models.CharField(max_length=100, blank=True)
    hjemmepoststed = models.CharField(max_length=100, blank=True)
    hjemmetelefon = models.CharField(max_length=100, blank=True)

    # Jobb og Utdanning
    jobb = models.CharField(max_length=100, blank=True)
    skole = models.CharField(max_length=100, blank=True)
    merknad = models.CharField(max_length=100, blank=True)

    # Utmerkelser
    dtp_ridder = models.IntegerField(blank=True, null=True)
    dtp_kommandor = models.IntegerField(blank=True, null=True)
    livsvarig_medlem = models.IntegerField(blank=True, null=True)
    mf58 = models.BooleanField()

    # Annet
    bilde = models.ImageField(blank=True, null=True)

    def navn(self):
        return self.fornavn + " " + self.etternavn

    def __str__(self):
        return self.navn()

    class Meta:
        verbose_name_plural = "Regifanter"


class Verv(models.Model):

    navn = models.CharField(max_length=100)
    prioritet = models.IntegerField()
    kort_beskrivelse = models.CharField(max_length=500)

    def __str__(self):
        return self.navn

    class Meta:
        verbose_name_plural = "Verv"

    '''
    @staticmethod
    def parse_from_csv():
        import csv
        with open("verv.csv", 'r') as f:
            reader = csv.reader(f)
            for line in reader:
                id, navn, pri, besk = line
                q = Verv(navn=navn, prioritet=pri, kort_beskrivelse=besk)
                q.save()
    '''


class Vervperiode(models.Model):
    verv = models.ForeignKey(Verv, on_delete=models.CASCADE)
    regifant = models.ForeignKey(Regifant, on_delete=models.CASCADE)
    aar = models.IntegerField()

    class Meta:
        verbose_name_plural = "Vervperioder"

    def __str__(self):
        return "%s - %s (%i)" % (self.regifant.navn(), self.verv.navn, self.aar)


class Uke(models.Model):
    ukenavn = models.CharField(max_length=100)
    aar = models.IntegerField()

    class Meta:
        verbose_name_plural = "Uker"

    def __str__(self):
        return self.ukenavn + " (" + str(self.aar) + ")"


class Ukeverv(models.Model):

    navn = models.CharField(max_length=100)
    kort_beskrivelse = models.CharField(max_length=500)

    def __str__(self):
        return self.navn

    class Meta:
        verbose_name_plural = "Ukeverv"


class Ukevervperiode(models.Model):
    ukeverv = models.ForeignKey(Ukeverv, on_delete=models.CASCADE)
    regifant = models.ForeignKey(Regifant, on_delete=models.CASCADE)
    uke = models.ForeignKey(Uke, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = "Ukevervperioder"

    def __str__(self):
        return "%s - %s (%s)" % (self.regifant.navn(), self.ukeverv.navn, self.uke)

felixdb/views.py
from django.shortcuts import render
from .models import Verv, Regifant, Vervperiode, Uke, Ukeverv, Ukevervperiode
from django.contrib.auth.decorators import login_required

@login_required
def index(request):
    regifanter = Regifant.objects.all()
    context = {
        "regifanter": regifanter
    }
    return render(request, 'felixdb/index.html', context)


@login_required
def regifant(request, regifant_id):
    regifant = Regifant.objects.get(pk=regifant_id)
    vervperiodeliste = Vervperiode.objects.filter(regifant=regifant).order_by('-aar')
    ukevervperiodeliste = Ukevervperiode.objects.filter(regifant=regifant)
    context={
        "regifant": regifant,
        "vervperiodeliste": vervperiodeliste,
        "ukevervperiodeliste": ukevervperiodeliste
    }
    return render(request, 'felixdb/regifant.html', context)


@login_required
def verv(request):
    vervliste = Verv.objects.order_by('navn')
    context = {'vervliste': vervliste}
    return render(request, 'felixdb/verv.html', context)


@login_required
def vervdetalj(request, verv_id):
    verv = Verv.objects.get(pk=verv_id)
    vervperioder = Vervperiode.objects.filter(verv=verv)
    context = {
        'verv': verv,
        'vervperioder': vervperioder,
    }
    return render(request, 'felixdb/vervdetalj.html', context)


@login_required
def ukeverv(request):
    ukevervliste = Ukeverv.objects.all()
    context = {
        'ukevervliste': ukevervliste
    }
    return render(request, 'felixdb/ukeverv.html', context)


@login_required
def ukevervdetalj(request, ukeverv_id):
    ukeverv = Ukeverv.objects.get(pk=ukeverv_id)
    ukevervperioder = Ukevervperiode.objects.filter(ukeverv=ukeverv)
    context = {
        'ukeverv': ukeverv,
        'ukevervperioder': ukevervperioder,
    }
    return render(request, 'felixdb/ukevervdetalj.html', context)


@login_required
def aarsoversikt(request, aar):
    vervperiodeliste = Vervperiode.objects.filter(aar=aar).order_by('-aar')
    context={
        "aar": aar,
        "vervperiodeliste": vervperiodeliste
    }
    return render(request, 'felixdb/aarsoversikt.html', context)


@login_required
def uker(request):
    uker = Uke.objects.all().order_by('-aar')
    context = {
        'uker': uker
    }
    return render(request, 'felixdb/uker.html', context)


@login_required
def ukedetalj(request, ukeaar):
    uke = Uke.objects.get(aar=ukeaar)
    ukevervperioder = Ukevervperiode.objects.filter(uke=uke)
    context = {
        'uke': uke,
        'ukevervperioder': ukevervperioder
    }
    return render(request, 'felixdb/ukedetalj.html', context)

templates/felixdb/aarsoversikt.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ aar }}</title>
</head>
<body>
    <h2>{{ aar }}</h2>
    <h3>verv</h3>
    <table>
        <tr>
            <th>Verv</th>
            <th>Person</th>
        </tr>
        {% for vervperiode in vervperiodeliste %}
            <tr>
                <td><a href={% url 'felixdb:vervdetalj' vervperiode.verv.pk%}>{{ vervperiode.verv }}</a></td>
                <td><a href={% url 'felixdb:regifant' vervperiode.regifant.pk%}>{{ vervperiode.regifant.navn }}</a></td>
            </tr>
        {% endfor %}
    </table>
</body>
</html>

templates/felixdb/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>FelixDB</title>
    {% load static %}
</head>
<body>

<h1>Velkommen til FelixDB</h1>
<h2>Nettsiden for generell pangpleie</h2>

<ul>
    {% for regifant in regifanter %}
        <li>
            <a href="{% url 'felixdb:regifant' regifant.pk %}">
                {{ regifant.navn }}
            </a>
        </li>
    {% endfor %}
</ul>
</body>
</html>

templates/felixdb/regifant.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ regifant.navn }}</title>
</head>
<body>

    <h2>{{ regifant.navn }}</h2>
    <img src="{{ regifant.bilde.url }}">
    <p>
        Info om denne regifanten
    </p>


    <h3>verv</h3>
    <table>
        <tr>
            <th>Verv</th>
            <th>år</th>
        </tr>
        {% for vervperiode in vervperiodeliste %}
            <tr>
                <td><a href={% url 'felixdb:vervdetalj' vervperiode.verv.pk%}>{{ vervperiode.verv }}</a></td>
                <td><a href={% url 'felixdb:aarsoversikt' vervperiode.aar %}>{{ vervperiode.aar }}</a></td>
            </tr>
        {% endfor %}
    </table>


    <h3>Ukeverv</h3>
    <table>
        <tr>
            <th>UKEverv</th>
            <th>UKE</th>
        </tr>
        {% for ukevervperiode in ukevervperiodeliste %}
            <tr>
                <td>
                    <a href={% url 'felixdb:ukevervdetalj' ukevervperiode.ukeverv.id %}>
                        {{ ukevervperiode.ukeverv }}
                    </a>
                </td>
                <td>
                    <a href={% url 'felixdb:ukedetalj' ukevervperiode.uke.aar %}>
                        {{ ukevervperiode.uke }}
                    </a>
                </td>
            </tr>
        {% endfor %}
    </table>
</body>
</html>

templates/felixdb/ukedetalj.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Verv</title>
</head>
<body>
    <h1> {{ uke }}</h1>

    <h3>Vervinnehavere</h3>
    <table>
        <tr>
            <th>Ukeverv</th>
            <th>Regifant</th>
        </tr>
        {% for ukevervperiode in ukevervperioder %}
            <tr>
                <td><a href="{% url 'felixdb:ukevervdetalj' ukevervperiode.ukeverv.id %}">
                    {{ ukevervperiode.ukeverv }}
                </a></td>
                <td><a href="{% url 'felixdb:regifant' ukevervperiode.regifant.id %}">
                    {{ ukevervperiode.regifant }}
                </a></td>
            </tr>
        {% endfor %}
    </table>

</body>
</html>

templates/felixdb/uker.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Uker</title>
</head>
<body>
    <h2>Uker</h2>
    <ul>
        {% for uke in uker %}
            <li> {{ uke }}</li>
        {% endfor %}
    </ul>
</body>
</html>

templates/felixdb/ukeverv.html
{% load static %}
<!DOCTYPE html>
<html lang="en">



<head>
    <title>Verv</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>




<body>
    <h2> UKEverv </h2>

    <ul>
        {% for ukeverv in ukevervliste %}
            <li>
                <a href="">
                    {{ ukeverv.navn }}
                </a>
            </li>
        {% endfor %}
    </ul>
</body>
</html>

templates/felixdb/ukevervdetalj.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Verv</title>
</head>
<body>
    <h1> {{ ukeverv.navn }}</h1>
    <p>
        {{ ukeverv.kort_beskrivelse }}
    </p>

    <h3>Vervinnehavere</h3>
    <table>
        <tr>
            <th>Uke</th>
            <th>Regifant</th>
        </tr>
        {% for ukevervperiode in ukevervperioder %}
            <tr>
                <td><a href={% url 'felixdb:ukedetalj' ukevervperiode.uke.aar %}>
                    {{ ukevervperiode.uke }}
                </a></td>
                <td><a href={% url 'felixdb:regifant' ukevervperiode.regifant.id %}>
                    {{ ukevervperiode.regifant }}
                </a></td>
            </tr>
        {% endfor %}
    </table>

</body>
</html>

templates/felixdb/verv.html
{% load static %}
<!DOCTYPE html>
<html lang="en">



<head>
    <title>Verv</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>




<body>
    <div class="page-header">
        FelixDB
    </div>
    <ul>
        {% for verv in vervliste %}
            <li>
                <a href="{% url 'vervdetalj' verv.pk %}">
                    {{ verv.navn }}
                </a>
            </li>
        {% endfor %}
    </ul>
</body>
</html>

templates/felixdb/vervdetalj.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Verv</title>
</head>
<body>
    <h1> {{ verv.navn }}</h1>
    <p>
        {{ verv.kort_beskrivelse }}
    </p>

    <h3>Vervinnehavere</h3>
    <table>
        <tr>
            <th>År</th>
            <th>Regifant</th>
        </tr>
        {% for vervperiode in vervperioder %}
            <tr>
                <td><a href={% url 'felixdb:aarsoversikt' vervperiode.aar %}>
                    {{ vervperiode.aar }}
                </a></td>
                <td><a href={% url 'felixdb:regifant' vervperiode.regifant.id %}>
                    {{ vervperiode.regifant }}
                </a></td>
            </tr>
        {% endfor %}
    </table>

</body>
</html>