hjem/urls.py
from django.urls import path
from . import views

app_name = 'hjem'
urlpatterns = [
    path('', views.index, name='index'),
    path('intern/', views.intern, name='intern'),
    path('kontakt/', views.kontakt, name='kontakt'),
    path('techspecs/', views.techspecs, name='techspecs'),
    path('om/', views.om, name='om')
]

regiweb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('intern/felixdb/', include('felixdb.urls')),
    path('intern/festkassen/', include('festkassen.urls')),
    path('intern/wiki/', include('wiki.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('hjem.urls')),
]

templates/generisk/ekstern_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Hjem</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'generisk/ekstern_base.css' %}">
</head>

<body>
<div class="wrapper">
    <header class="header">
        <a href="{% url 'hjem:index' %}">
            <img class ="logo" src="{% static 'generisk/regilogo.png' %}">
        </a>

        <nav class="nav">
            <div></div>
            <a class="link" href="{% url 'hjem:kontakt' %}">kontakt</a>
            <a class="link" href="{% url 'hjem:techspecs' %}">techspecs</a>
            <a class="link" href="{% url 'hjem:om' %}">om oss</a>
            <a class="link" href="{% url 'hjem:intern' %}">intern</a>
        </nav>
    </header>
    <div class="main">
        {% block content %}
        {% endblock %}
    </div>
    <div class="footer">
    </div>
</div>
</body>
</html>

templates/generisk/intern_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>