festkassen/urls.py
from django.urls import path
from . import views

app_name = 'festkassen'
urlpatterns = [

    # offentlig
    path('', views.forside, name='forside'),
    path('innskudd/', views.innskudd, name='innskudd'),

    # Forside for admin
    path('admin/', views.admin, name='admin'),

    # Godkjenne innskudd
    path('admin/innskudd', views.admin_innskudd, name='admin_innskudd'),
    path('admin/godkjenn_innskudd/<int:innskudd_pk>', views.admin_godkjenn_innskudd, name='admin_godkjenn_innskudd'),

    # Interne krysselister
    path('admin/krysselister', views.admin_interne_krysselister, name='admin_interne_krysselister'),
    path('admin/krysselister/<int:krysseliste_pk>', views.admin_rediger_krysseliste, name='admin_rediger_krysseliste'),
    path('admin/krysselister/<int:krysseliste_pk>/slett/<int:kryss_pk>', views.admin_slett_kryss, name='admin_slett_kryss'),

    # BSFer
    path('admin/bsf', views.admin_bsfer, name='admin_bsfer'),
    path('admin/bsf/<int:bsf_pk>', views.admin_rediger_bsf, name='admin_rediger_bsf'),
    path('admin/bsf/<int:bsf_pk>/liste/<int:liste_pk>', views.admin_rediger_ekstern_liste, name='admin_rediger_ekstern_liste'),
]

hjem/urls.py
from django.urls import path
from . import views

app_name = 'hjem'
urlpatterns = [
    path('', views.index, name='index'),
    path('intern/', views.intern, name='intern'),
    path('kontakt/', views.kontakt, name='kontakt'),
    path('techspecs/', views.techspecs, name='techspecs'),
    path('om/', views.om, name='om')
]

regiweb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('intern/felixdb/', include('felixdb.urls')),
    path('intern/festkassen/', include('festkassen.urls')),
    path('intern/wiki/', include('wiki.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('hjem.urls')),
]

festkassen/views/admin.py
from django.shortcuts import render
from ..models import Festkassekonto, Innskudd, Krysseliste
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required, user_passes_test
from django.urls import reverse
from django import forms


def har_brukeren_festkassekonto(user):
    return Festkassekonto.objects.filter(regiweb_bruker=user).exists()


def er_festkasse(user):
    return user.groups.filter(name='Festkasse').exists()


@login_required
@user_passes_test(er_festkasse)
def admin(request):
    context = {}
    return render(request, 'festkassen/admin.html', context)

festkassen/views/admin_bsf.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required, user_passes_test
from django import forms

from ..models import BSF, Eksternkrysseliste
from .admin import er_festkasse


class NyBsfSkjema(forms.ModelForm):
    class Meta:
        model = BSF
        fields = ('beskrivelse', 'dato')
        widgets = {
            'dato': forms.DateInput(attrs={'type': 'date'})
        }


class NyEksternlisteSkjema(forms.ModelForm):
    class Meta:
        model = Eksternkrysseliste
        fields = ('dato', 'bar')
        widgets = {
            'dato': forms.DateInput(attrs={'type': 'date'})
        }


@login_required
@user_passes_test(er_festkasse)
def admin_bsfer(request):

    bsfer = BSF.objects.all().order_by('-dato')[:30]
    nybsfskjema = NyBsfSkjema()
    context = {
        'bsfer': bsfer,
        'nybsfskjema': nybsfskjema,
    }

    if request.method == 'POST':
        nybsfskjema = NyBsfSkjema(request.POST)
        if nybsfskjema.is_valid():
            ny_bsf = BSF(
                beskrivelse=nybsfskjema.cleaned_data['beskrivelse'],
                dato=nybsfskjema.cleaned_data['dato']
            )
            ny_bsf.save()
            tilbakemelding = "Ny BSF registrert: %s" % (
                ny_bsf,
            )
            context.update({
                'tilbakemelding': tilbakemelding
            })

    return render(request, 'festkassen/admin_bsfer.html', context)


@login_required
@user_passes_test(er_festkasse)
def admin_rediger_bsf(request, bsf_pk):
    eksternlister = Eksternkrysseliste.objects.filter(bsf=bsf_pk)
    bsf = BSF.objects.get(pk=bsf_pk)
    nyeksternlisteskjema = NyEksternlisteSkjema()

    context = {
        'bsf': bsf,
        'eksternlister': eksternlister,
        'nyEksternlisteSkjema': nyeksternlisteskjema
    }

    if request.method == 'POST':
        nyeksternlisteskjema = NyEksternlisteSkjema(request.POST)
        if nyeksternlisteskjema.is_valid():
            ny_eksternliste = Eksternkrysseliste(
                dato=nyeksternlisteskjema.cleaned_data['dato'],
                bar=nyeksternlisteskjema.cleaned_data['bar'],
                bsf=bsf
            )
            ny_eksternliste.save()
            tilbakemelding = "Ny Eksternliste registrert: %s" % (
                ny_eksternliste,
            )
            context.update({
                'tilbakemelding': tilbakemelding
            })
    return render(request, 'festkassen/admin_rediger_bsf.html', context)

festkassen/views/admin_eksterne_lister.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required, user_passes_test
from django import forms

from ..models import BSF, Eksternkrysseliste, EksternTransaksjon, EksternDranker
from .admin import er_festkasse


class NyEksternlisteSkjema(forms.ModelForm):
    class Meta:
        model = Eksternkrysseliste
        fields = ('bar', 'bsf')
        widgets = {
            'dato': forms.DateInput(attrs={'type': 'date'})
        }


@login_required
@user_passes_test(er_festkasse)
def admin_rediger_ekstern_liste(request, bsf_pk, liste_pk):

    kryss = EksternTransaksjon.objects.filter(eksternkrysseliste=liste_pk)
    bsf = BSF.objects.get(pk=bsf_pk)
    eksternliste = Eksternkrysseliste.objects.get(pk=liste_pk)
    varer_paa_lista = Eksternkrysseliste.bar.varer_paa_listene.all()

    context = {
        'kryss': kryss,
        'bsf': bsf,
        'eksternliste': eksternliste,
        'varer_paa_lista': varer_paa_lista
    }

    if request.method == "POST":
        print(request.POST)
    return render(request, 'festkassen/admin_rediger_ekstern_liste.html', context)

festkassen/views/admin_innskudd.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required, user_passes_test
from django.urls import reverse

from ..models import Innskudd, Krysseliste
from .admin import er_festkasse


@login_required
@user_passes_test(er_festkasse)
def admin_innskudd(request):
    ventende_innskudd = Innskudd.objects.filter(godkjent=False).order_by('-tidsstempel')
    godkjente_innskudd = Innskudd.objects.filter(godkjent=True).order_by('-tidsstempel')[:30]
    context = {
        'ventende_innskudd': ventende_innskudd,
        'godkjente_innskudd': godkjente_innskudd,
    }
    return render(request, 'festkassen/admin_innskudd.html', context)


@login_required
@user_passes_test(er_festkasse)
def admin_godkjenn_innskudd(request, innskudd_pk):
    godkjent_innskudd = Innskudd.objects.get(pk=innskudd_pk)
    godkjent_innskudd.godkjent = True
    godkjent_innskudd.save()

    return HttpResponseRedirect(reverse('festkassen:admin_innskudd'))

festkassen/views/admin_interne_lister.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required, user_passes_test
from django import forms

from ..models import Festkassekonto, Kryss, Krysseliste, Vare
from .admin import er_festkasse


class NyKrysselisteSkjema(forms.ModelForm):
    class Meta:
        model = Krysseliste
        fields = ('listedato', 'type')
        widgets = {
            'listedato': forms.DateInput(attrs={'type': 'date'})
        }


@login_required
@user_passes_test(er_festkasse)
def admin_interne_krysselister(request):

    krysselister = Krysseliste.objects.all().order_by('-listedato')[:30]
    nykrysselisteskjema = NyKrysselisteSkjema()
    context = {
        'krysselister': krysselister,
        'nykrysselisteskjema': nykrysselisteskjema,
    }

    if request.method == 'POST':
        nykrysselisteskjema = NyKrysselisteSkjema(request.POST)
        if nykrysselisteskjema.is_valid():
            ny_krysseliste = Krysseliste(
                listedato=nykrysselisteskjema.cleaned_data['listedato'],
                type=nykrysselisteskjema.cleaned_data['type'],
                opprettet_av=request.user,
            )
            ny_krysseliste.save()
            tilbakemelding = "Ny krysseliste registrert: %s" % (
                ny_krysseliste,
            )
            context.update({
                'tilbakemelding': tilbakemelding
            })

    return render(request, 'festkassen/admin_interne_krysselister.html', context)


@login_required
@user_passes_test(er_festkasse)
def admin_rediger_krysseliste(request, krysseliste_pk):
    kryss = Kryss.objects.filter(krysseliste=krysseliste_pk)
    krysseliste = Krysseliste.objects.get(pk=krysseliste_pk)
    kontoer = krysseliste.type.festkassekontoer_paa_lista.all()
    varer = krysseliste.type.varer.all()
    varenavn = [vare.navn for vare in varer]

    context = {
        'kryss': kryss,
        'krysseliste': krysseliste,
        'varer': varer,
        'kontoer': kontoer
    }

    if request.method == "POST":
        konto = Festkassekonto.objects.get(pk=int(request.POST['konto']))

        # Filtrerer ut alle key-value-par i request.POST som ikke er gyldige varer,
        # og sørger for at alle kryss er heltall og ikke strings
        # Det finnes garantert en bedre måte å gjøre dette på :P
        nye_kryss = {vare: int(request.POST[vare]) for vare in varenavn if int(request.POST[vare]) > 0}

        for navn in nye_kryss:
            vare = Vare.objects.get(navn=navn)
            nytt_kryss = Kryss(
                festkassekonto=konto,
                vare=vare,
                antall=nye_kryss[navn],
                stykkpris=vare.standardpris,
                krysseliste=krysseliste
            )
            nytt_kryss.save()

    return render(request, 'festkassen/admin_rediger_krysseliste.html', context)


@login_required
@user_passes_test(er_festkasse)
def admin_slett_kryss(request, krysseliste_pk, kryss_pk):
    Kryss.objects.get(pk=kryss_pk).delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))

festkassen/views/offentlig.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required, user_passes_test
from django import forms

from ..models import Festkassekonto, Innskudd, BSFregning, Kryss
from .admin import har_brukeren_festkassekonto


class Innskuddskjema(forms.Form):
    sum = forms.DecimalField(max_digits=9, decimal_places=2, min_value=0)
    kommentar = forms.CharField(max_length=200, required=False)


@login_required
@user_passes_test(har_brukeren_festkassekonto)
def forside(request):

    # Hent transaksjonsdata fra festkassens backend
    festkassekonto = Festkassekonto.objects.get(regiweb_bruker=request.user)
    innskudd = Innskudd.objects.filter(festkassekonto=festkassekonto).order_by('-tidsstempel')
    bsf_regninger = BSFregning.objects.filter(festkassekonto=festkassekonto).order_by('-tidsstempel')
    kryss = Kryss.objects.filter(festkassekonto=festkassekonto).order_by('-tidsstempel')
    saldo = festkassekonto.saldo()

    context = {
        'innskudd': innskudd,
        'bsf_regninger': bsf_regninger,
        'kryss': kryss,
        'saldo': saldo
    }

    return render(request, 'festkassen/forside.html', context)


@login_required
@user_passes_test(har_brukeren_festkassekonto)
def innskudd(request):

    festkassekonto = Festkassekonto.objects.filter(regiweb_bruker=request.user).first()
    innskuddskjema = Innskuddskjema()
    context = {
        'festkassekonto': festkassekonto,
        'innskuddskjema': innskuddskjema
    }

    if request.method == 'POST':
        innskuddskjema = Innskuddskjema(request.POST)
        if innskuddskjema.is_valid():
            nytt_innskudd = Innskudd(
                belop=innskuddskjema.cleaned_data['sum'],
                kommentar=innskuddskjema.cleaned_data['kommentar'],
                festkassekonto=festkassekonto
            )
            nytt_innskudd.save()
            tilbakemelding = "innskudd på %s registrert på %s med ID %s" % (
                nytt_innskudd.belop,
                festkassekonto.regiweb_bruker.get_full_name(),
                nytt_innskudd.pk,
            )
            context.update({
                'tilbakemelding': tilbakemelding
            })

    return render(request, 'festkassen/innskudd.html', context)

templates/festkassen/admin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Festkassens adminside</title>
</head>
<body>
    <h3>Bare for festkasse</h3>
    <ul>
        <li><a href="{% url 'festkassen:admin_innskudd' %}">Godkjenn innskudd</a></li>
        <li><a href="{% url 'festkassen:admin_interne_krysselister' %}">Se og endre interne krysselister</a></li>
        <li><a href="{% url 'festkassen:admin_bsfer' %}">Se og endre BSFer </a></li>
    </ul>
</body>
</html>

templates/festkassen/admin_bsfer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% if tilbakemelding %}
    <h2> {{ tilbakemelding }} </h2>
{% endif %}
<div>
    <form action="{% url 'festkassen:admin_bsfer' %}" method="post">
        {% csrf_token %}
        {{ nybsfskjema.as_p }}
        <input type="submit" value="registrer">
    </form>
</div>
<table>
        <tr>
            <th>Dato</th>
            <th>Kommentar</th>
            <th></th>
        </tr>
        {% for bsf in bsfer %}
            <tr>
                <td>{{ bsf.dato }}</td>
                <td>{{ bsf.beskrivelse }}</td>
                <td><a href={% url 'festkassen:admin_rediger_bsf' bsf.pk %}>rediger</a></td>
            </tr>
        {% endfor %}
    </table>
</body>
</html>

templates/festkassen/admin_innskudd.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <table>
        <tr>
            <th></th>
            <th>ID</th>
            <th>Festkassekonto</th>
            <th>Dato</th>
            <th>Sum</th>
            <th>kommentar</th>
        </tr>
        {% for i in ventende_innskudd %}
            <tr>
                <td>
                    <a href="{% url 'festkassen:admin_godkjenn_innskudd' i.pk %}">
                        <button>&#10003</button>
                    </a>
                </td>
                <td>{{ i.pk }}</td>
                <td>{{ i.festkassekonto }}</td>
                <td>{{ i.tidsstempel }}</td>
                <td>{{ i.sum }}</td>
                <td>{{ i.kommentar }}</td>
            </tr>
        {% endfor %}
    </table>
    <h2>godkjente innskudd</h2>
    <table>
        <tr>
            <th>ID</th>
            <th>Festkassekonto</th>
            <th>Dato</th>
            <th>Sum</th>
            <th>kommentar</th>
        </tr>
        {% for i in godkjente_innskudd %}
            <tr>
                <td>{{ i.pk }}</td>
                <td>{{ i.festkassekonto }}</td>
                <td>{{ i.tidsstempel }}</td>
                <td>{{ i.sum }}</td>
                <td>{{ i.kommentar }}</td>
            </tr>
        {% endfor %}
    </table>
</body>
</html>

templates/festkassen/admin_interne_krysselister.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% if tilbakemelding %}
    <h2> {{ tilbakemelding }} </h2>
{% endif %}
<div>
    <form action="{% url 'festkassen:admin_interne_krysselister' %}" method="post">
        {% csrf_token %}
        {{ nykrysselisteskjema.as_p }}
        <input type="submit" value="registrer">
    </form>
</div>
<table>
        <tr>
            <th>ID</th>
            <th>Listedato</th>
            <th>Type</th>
            <th></th>
        </tr>
        {% for krysseliste in krysselister %}
            <tr>
                <td>{{ krysseliste.pk }}</td>
                <td>{{ krysseliste.listedato }}</td>
                <td>{{ krysseliste.type }}</td>
                <td><a href={% url 'festkassen:admin_rediger_krysseliste' krysseliste.pk%}>rediger</a></td>
            </tr>
        {% endfor %}
    </table>
</body>
</html>

templates/festkassen/admin_krysselister.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% if tilbakemelding %}
    <h2> {{ tilbakemelding }} </h2>
{% endif %}
<div>
    <form action="{% url 'festkassen:admin_krysselister' %}" method="post">
        {% csrf_token %}
        {{ nykrysselisteskjema.as_p }}
        <input type="submit" value="registrer">
    </form>
</div>
<table>
        <tr>
            <th>ID</th>
            <th>Listedato</th>
            <th>Type</th>
        </tr>
        {% for krysseliste in krysselister %}
            <tr>
                <td>{{ krysseliste.pk }}</td>
                <td>{{ krysseliste.listedato }}</td>
                <td>{{ krysseliste.type }}</td>
            </tr>
        {% endfor %}
    </table>
</body>
</html>

templates/festkassen/admin_rediger_bsf.html
<!DOCTYPE html>
<html lang="en">


<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>


<body>
    <h2>{{ bsf.dato }} - {{ bsf.beskrivelse }}</h2>

    <form action="{% url 'festkassen:admin_rediger_bsf' bsf.pk %}" method="post">
        {% csrf_token %}
        {{ nyEksternlisteSkjema.as_p }}
        <input type="submit" value="registrer">
    </form>

    <table>
        <tr>
            <th> Bar </th>
            <th> Dato </th>
            <th></th>
        </tr>
        {% for eksternliste in eksternlister %}
            <tr>
                <td>{{ eksternliste.bar }}</td>
                <td>{{ eksternliste.dato }}</td>
                <td><a href="{% url 'festkassen:admin_rediger_ekstern_liste' bsf.pk eksternliste.pk %}"> Rediger </a></td>
            </tr>
        {% endfor %}
    </table>
</body>
</html>

templates/festkassen/admin_rediger_ekstern_liste.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1> {{ bsf.dato }} - {{ bsf.beskrivelse }} -> {{ eksternliste.bar }}</h1>
{% if tilbakemelding %}
    <h2> {{ tilbakemelding }} </h2>
{% endif %}

<h3>Registrer nye eksternkryss</h3>
<form action="{% url 'festkassen:admin_rediger_ekstern_liste' bsf.pk eksternliste.pk %}" method="post">
    {% csrf_token %}
    {{ nytteksternkryssskjema.as_p }}
    <input type="submit" value="registrer">
</form>

<table>
        <tr>
            <th>Person</th>
            <th>Vare</th>
            <th>Antall</th>
            <th>Stykkpris</th>
            <th>Sum</th>
            <th></th>
        </tr>
        {% for enkeltkryss in kryss %}
            <tr>
                <td>{{ enkeltkryss.person }}</td>
                <td>{{ enkeltkryss.vare }}</td>
                <td>{{ enkeltkryss.antall }}</td>
                <td>{{ enkeltkryss.stykkpris }}</td>
                <td>{{ enkeltkryss.sum }}</td>
            </tr>
        {% endfor %}
    </table>
</body>
</html>

templates/festkassen/admin_rediger_krysseliste.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h2>{{ krysseliste }}</h2>
    <table>
        <tr>
            <th> Konto</th>
            <th> Vare </th>
            <th> Antall </th>
            <th> Stykkpris </th>
            <th> Sum </th>
            <th></th>
        </tr>
        {% for enkeltkryss in kryss %}
            <tr>
                <td>{{ enkeltkryss.festkassekonto }}</td>
                <td>{{ enkeltkryss.vare }}</td>
                <td>{{ enkeltkryss.antall }}</td>
                <td>{{ enkeltkryss.stykkpris }}</td>
                <td>{{ enkeltkryss.sum }}</td>
                <td> <a href= {% url 'festkassen:admin_slett_kryss' krysseliste.pk enkeltkryss.pk %}> Slett </a></td>
            </tr>
        {% endfor %}
    </table>

    <form action="{% url 'festkassen:admin_rediger_krysseliste' krysseliste.pk%}" method="post">
        {% csrf_token %}
        <label for="konto">Konto</label>
        <select id="konto" name="konto" autofocus>
            {% for konto in kontoer %}
                <option value={{ konto.pk }}>{{ konto }}</option>
            {% endfor %}
        </select>
        <p>
        {% for vare in varer %}
            <label for="{{ vare.navn }}">{{ vare.navn }}</label>
            <input type="number" name="{{ vare.navn }}" id="{{ vare.navn }}" value=0>
        {% endfor %}
        </p>

        <input type="submit" value="Registrer">
    </form>
</body>
</html>

templates/festkassen/forside.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Festkassen</title>
</head>
<body>

    <h2>Forside for festkassen</h2>
    <a href="{% url 'festkassen:innskudd' %}">Innskudd</a>
    <a href="{% url 'festkassen:admin' %}">admin</a>

    <h2>saldo = {{ saldo }}</h2>

    <h3> Siste innskudd &#10003</h3>
    <table>
        <tr>
            <th>Tidsstempel</th>
            <th>Sum</th>
            <th>Godkjent</th>
        </tr>
        {% for i in innskudd %}
            <tr>
                <td>{{ i.tidsstempel }}</td>
                <td>{{ i.sum }}</td>
                <td>
                    {% if i.godkjent %}
                        &#10003 <!-- checkmark-->
                    {% else %}
                        &#10060 <!-- kryss-->
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
    </table>

    <h3> Siste BSF-regninger </h3>
    <table>
        <tr>
            <th>Tidsstempel</th>
            <th>Sum</th>
            <th>Bar</th>
            <th>BSF</th>
        </tr>
        {% for i in bsf_regninger %}
            <tr>
                <td>{{ i.tidsstempel }}</td>
                <td>{{ i.sum }}</td>
                <td>{{ i.bar }}</td>
                <td>{{ i.bsf }}</td>
            </tr>
        {% endfor %}
    </table>

    <h3> Siste kryss </h3>
    <table>
        <tr>
            <th>Tidsstempel</th>
            <th>Vare</th>
            <th>Antall</th>
            <th>sum</th>
            <th>Krysseliste</th>
        </tr>
        {% for i in kryss %}
            <tr>
                <td>{{ i.tidsstempel }}</td>
                <td>{{ i.vare }}</td>
                <td>{{ i.antall }}</td>
                <td>{{ i.sum }}</td>
                <td>{{ i.krysseliste }}</td>
            </tr>
        {% endfor %}
    </table>
</body>
</html>

templates/festkassen/ingen_festkassekonto.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Ingen festkassekonto</title>
</head>
<body>
    <h2> Ingen festkassekonto assosiert med denne brukeren</h2>
</body>
</html>

templates/festkassen/innskudd.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Innskudd</title>
</head>
<body>
    <h2> Innskudd for {{ user.get_full_name }}</h2>
    {% if tilbakemelding %}
        <h3>{{ tilbakemelding }}</h3>
    {% endif %}
    <form action="{% url 'festkassen:innskudd' %}" method="post">
        {% csrf_token %}
        {{ innskuddskjema }}
        <input type="submit" value="register">
    </form>
</body>
</html>