felixdb/urls.py
from django.urls import path
from . import views

app_name = 'felixdb'
urlpatterns = [
    path('', views.index, name='index'),
    path('regifant/<int:regifant_id>/', views.regifant, name='regifant'),
    path('verv/', views.verv, name="verv"),
    path('verv/<int:verv_id>/', views.vervdetalj, name='vervdetalj'),
    path('ukeverv/', views.ukeverv, name="ukeverv"),
    path('ukeverv/<int:ukeverv_id>', views.ukevervdetalj, name="ukevervdetalj"),
    path('aarsoversikt/<int:aar>/', views.aarsoversikt, name='aarsoversikt'),
    path('uker/', views.uker, name='uker'),
    path('uker/<int:ukeaar>', views.ukedetalj, name='ukedetalj'),
]

festkassen/urls.py
from django.urls import path
from . import views

app_name = 'festkassen'
urlpatterns = [

    # offentlig
    path('', views.forside, name='forside'),
    path('innskudd/', views.innskudd, name='innskudd'),

    # Forside for admin
    path('admin/', views.admin, name='admin'),

    # Godkjenne innskudd
    path('admin/innskudd', views.admin_innskudd, name='admin_innskudd'),
    path('admin/godkjenn_innskudd/<int:innskudd_pk>', views.admin_godkjenn_innskudd, name='admin_godkjenn_innskudd'),

    # Interne krysselister
    path('admin/krysselister', views.admin_interne_krysselister, name='admin_interne_krysselister'),
    path('admin/krysselister/<int:krysseliste_pk>', views.admin_rediger_krysseliste, name='admin_rediger_krysseliste'),
    path('admin/krysselister/<int:krysseliste_pk>/slett/<int:kryss_pk>', views.admin_slett_kryss, name='admin_slett_kryss'),

    # BSFer
    path('admin/bsf', views.admin_bsfer, name='admin_bsfer'),
    path('admin/bsf/<int:bsf_pk>', views.admin_rediger_bsf, name='admin_rediger_bsf'),
    path('admin/bsf/<int:bsf_pk>/liste/<int:liste_pk>', views.admin_rediger_ekstern_liste, name='admin_rediger_ekstern_liste'),
]

hjem/urls.py
from django.urls import path
from . import views

app_name = 'hjem'
urlpatterns = [
    path('', views.index, name='index'),
    path('intern/', views.intern, name='intern'),
    path('kontakt/', views.kontakt, name='kontakt'),
    path('techspecs/', views.techspecs, name='techspecs'),
    path('om/', views.om, name='om')
]

regiweb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('intern/felixdb/', include('felixdb.urls')),
    path('intern/festkassen/', include('festkassen.urls')),
    path('intern/wiki/', include('wiki.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('hjem.urls')),
]

wiki/urls.py
from django.urls import path
from . import views

app_name = 'wiki'
urlpatterns = [
    path('', views.WikisideListView.as_view(), name='index'),
    path('ny/', views.WikisideCreateView.as_view(), name='wikiside_create'),
    path('<slug:slug>/', views.WikisideDetailView.as_view(), name='wikiside'),
    path('<slug:slug>/ny/', views.RevisjonCreateView.as_view(), name='revisjon_create'),
]

hjem/models.py
from django.db import models

# Create your models here.

hjem/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from felixdb.models import Regifant
# Create your views here.

def index(request):
    context = {}
    return render(request, 'hjem/index.html', context)

def kontakt(request):
    aktive_regifanter = Regifant.objects.filter(er_aktiv=True)
    context = {'aktive_regifanter': aktive_regifanter}
    return render(request, 'hjem/kontakt.html', context)

def techspecs(request):
    context = {}
    return render(request, 'hjem/techspecs.html', context)

def om(request):
    context = {}
    return render(request, 'hjem/om.html', context)

@login_required
def intern(request):
    context = {}
    return render(request, 'hjem/intern.html', context)

templates/hjem/index.html
<!DOCTYPE html>
<html lang="en">

{% extends 'generisk/ekstern_base.html' %}

{% load static %}


{% block content %}
    <h2>Regi v3.0</h2>
{% endblock %}
</html>

templates/hjem/intern.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Hjem</title>
</head>
<body>
    <h2> velkommen til Regi internsider</h2>

    {% if user.is_authenticated %}
        <p> du er logget in som {{ user.username }}</p>
        <p><a href="{% url 'logout' %}">logg ut</a> </p>
    {% else %}
        <p> Du er ikke logget inn</p>
        <p> <a href="{% url 'login' %}"> logg inn </a></p>
    {% endif %}


    <ul>
        <li><a href="{% url 'felixdb:index' %}"> FelixDB </a> </li>
        <li><a href="{% url 'festkassen:forside' %}"> Festkassen </a> </li>
        <li><a href="{% url 'wiki:index' %}"> Wiki </a> </li>
    </ul>
</body>
</html>

templates/hjem/kontakt.html
<!DOCTYPE html>
</html>

{% extends 'generisk/ekstern_base.html' %}

{% block content %}
    <h2>Kontaktinfo</h2>
    <p>
        her kommer det masse kontaktinfo
    </p>
{% endblock %}
</html>

templates/hjem/om.html
<!DOCTYPE html>
</html>

{% extends 'generisk/ekstern_base.html' %}

{% block content %}
    <h2>Om oss</h2>
    <p> Regi er Studentersamfundet i Trondhjems lys-
        og scenetekniske gjeng. Dette innebærer at vi kjører lys på konserter
        og teater i Storsalen, Klubben og Knaus, og sørger for at disse scenene
        til enhver tid er i god teknisk stand. I lyskasterparken vår inngår
        nærmere 200 konvensjonelle lyskastere, samt en hel del teknisk
        avanserte duppedingser (deriblandt moving og flere velrenommerte
        lysbord (detaljer). For å beholde det nødvendige tekniske kompetansenivået
        i gjengen har vi en bindingstid på tre år for alle våre aktive.
        Regi disponerer også et fullverdig mekanisk verksted og en elektrolab,
        hvor vi lager og vedlikeholder nytt og gammelt utstyr.
        Vi er i dag 19 aktive medlemmer i gjengen,
        som alle har funksjonærstatus på huset.
        Alt arbeid skjer selvfølgelig på ideell basis
    </p>
{% endblock %}
</html>

templates/hjem/techspecs.html
<!DOCTYPE html>
</html>

{% extends 'generisk/ekstern_base.html' %}

{% block content %}
    <h2>Tech specs</h2>
    <p>
        her kommer det masse techspecs og greier
    </p>
{% endblock %}
</html>